//! Minecraft modules

pub mod auth;
pub mod community;
pub mod download;
pub mod fools;
pub mod image_cache;
pub mod isolation;
pub mod java;
pub mod java_selector;
pub mod language;
pub mod launch;
pub mod launcher_profiles;
pub mod loaders;
pub mod online;
pub mod skin;
pub mod sources;
pub mod system;
pub mod utils;
pub mod version;
