//! 静态关键字规则表（数据驱动）

use super::super::super::types::CrashCategory;
use super::types::{KeywordRule, SourceKind};

/// 关键字规则表（数据驱动）
///
/// 置信度反映证据可靠程度：精准关键字（0.90-0.95）＞ 启发式堆栈（0.80）＞ 宽松规则（0.50-0.75）。
/// 评分器按置信度取最高者，并列时取规则表中靠前的条目。
pub const KEYWORD_RULES: &[KeywordRule] = &[
    // ── 运行时日志：JVM / 显卡 / 内存 ──
    KeywordRule {
        id: "jvm_unknown_option",
        source: SourceKind::RuntimeLog,
        patterns: &["unrecognized option:"],
        and_patterns: &[],
        category: CrashCategory::Java,
        confidence: 0.95,
        reason: "启动参数中包含 Java 无法识别的选项",
        suggestion: "JVM 在解析启动参数时遇到了未知选项。\n建议检查启动设置中的自定义 JVM 参数，或将其清空后重试。",
    },
    KeywordRule {
        id: "jvm_create_failed",
        source: SourceKind::RuntimeLog,
        patterns: &["could not create the java virtual machine"],
        and_patterns: &[],
        category: CrashCategory::Java,
        confidence: 0.95,
        reason: "Java 虚拟机未能成功创建",
        suggestion: "JVM 启动失败，可能由参数冲突或所选 Java 异常导致。\n请尝试更换 Java 版本或检查 JVM 参数配置。",
    },
    KeywordRule {
        id: "gpu_no_opengl",
        source: SourceKind::RuntimeLog,
        patterns: &["the driver does not appear to support opengl"],
        and_patterns: &[],
        category: CrashCategory::Graphics,
        confidence: 0.95,
        reason: "显卡驱动未能提供 OpenGL 支持",
        suggestion: "当前显卡驱动无法满足游戏的 OpenGL 渲染需求。\n请升级显卡驱动；若使用独立显卡，请确认 Java 正以高性能模式运行。",
    },
    KeywordRule {
        id: "gpu_pixel_format",
        source: SourceKind::RuntimeLog,
        patterns: &["couldn't set pixel format"],
        and_patterns: &[],
        category: CrashCategory::Graphics,
        confidence: 0.95,
        reason: "像素格式设置失败（显卡驱动问题）",
        suggestion: "游戏窗口无法按所需像素格式初始化，通常与显卡驱动有关。\n请更新显卡驱动，或在启动设置中关闭「使用高性能显卡」选项。",
    },
    KeywordRule {
        id: "java_openj9",
        source: SourceKind::RuntimeLog,
        patterns: &["open j9 is not supported", "openj9 is incompatible", ".j9vminternals."],
        and_patterns: &[],
        category: CrashCategory::Java,
        confidence: 0.95,
        reason: "OpenJ9 虚拟机与游戏不兼容",
        suggestion: "游戏依赖 HotSpot 虚拟机，无法在 OpenJ9 环境下运行。\n请更换为 HotSpot 发行版的 Java 后再启动。",
    },
    KeywordRule {
        id: "mem_oom",
        source: SourceKind::RuntimeLog,
        patterns: &["java.lang.outofmemoryerror", "an out of memory error"],
        and_patterns: &[],
        category: CrashCategory::Memory,
        confidence: 0.95,
        reason: "游戏内存不足",
        suggestion: "Minecraft 运行时的内存已耗尽。\n请在启动设置中提高游戏内存分配，并关闭其他高内存占用的程序。",
    },
    KeywordRule {
        id: "mem_reserve_32bit",
        source: SourceKind::RuntimeLog,
        patterns: &["could not reserve enough space"],
        and_patterns: &["for 1048576kb object heap"],
        category: CrashCategory::Java,
        confidence: 0.95,
        reason: "32 位 Java 无法分配 1GB 堆内存",
        suggestion: "32 位 JVM 的地址空间不足以分配所需堆内存。\n请更换为 64 位 Java 后重试。",
    },
    KeywordRule {
        id: "mem_reserve_failed",
        source: SourceKind::RuntimeLog,
        patterns: &["could not reserve enough space"],
        and_patterns: &[],
        category: CrashCategory::Memory,
        confidence: 0.90,
        reason: "JVM 无法预留足够的堆内存空间",
        suggestion: "系统无法为 JVM 预留所请求的内存。\n建议降低游戏内存分配，或关闭部分占用内存的程序后再试。",
    },
    KeywordRule {
        id: "gpu_gl_1282",
        source: SourceKind::RuntimeLog,
        patterns: &["1282: invalid operation"],
        and_patterns: &[],
        category: CrashCategory::Graphics,
        confidence: 0.90,
        reason: "OpenGL 1282 错误（光影或资源包疑似所致）",
        suggestion: "渲染过程中触发了 OpenGL 非法操作错误。\n请尝试移除最近添加的光影或资源包后重新启动。",
    },
    // ── 运行时日志：Mod 相关 ──
    KeywordRule {
        id: "mod_duplicate",
        source: SourceKind::RuntimeLog,
        patterns: &["duplicate mod", "duplicate mods found"],
        and_patterns: &[],
        category: CrashCategory::Mod,
        confidence: 0.90,
        reason: "检测到重复安装的 Mod",
        suggestion: "mods 目录中存在重复的 Mod 文件。\n请检查并移除重复项后重启游戏。",
    },
    KeywordRule {
        id: "mod_missing_dependency",
        source: SourceKind::RuntimeLog,
        patterns: &["missing or unsupported mandatory dependencies"],
        and_patterns: &[],
        category: CrashCategory::Mod,
        confidence: 0.90,
        reason: "Mod 前置缺失或与当前版本不匹配",
        suggestion: "某个 Mod 依赖的前置 Mod 缺失，或与当前游戏版本不兼容。\n请核对各 Mod 的前置要求与版本兼容性。",
    },
    KeywordRule {
        id: "java_jdk_not_jre",
        source: SourceKind::RuntimeLog,
        patterns: &["java.lang.classcastexception: java.base/jdk"],
        and_patterns: &[],
        category: CrashCategory::Java,
        confidence: 0.90,
        reason: "当前 Java 为 JDK 而非 JRE 导致崩溃",
        suggestion: "JDK 环境可能引发该类型转换异常。\n建议更换为 JRE 发行版的 Java 后再启动。",
    },
    KeywordRule {
        id: "fabric_resolution_failed",
        source: SourceKind::RuntimeLog,
        patterns: &["mod resolution failed"],
        and_patterns: &[],
        category: CrashCategory::Fabric,
        confidence: 0.75,
        reason: "Mod 解析失败",
        suggestion: "Fabric 加载器无法完成 Mod 依赖解析。\n请确认各 Mod 与当前 MC 版本、Fabric API 版本兼容。",
    },
    KeywordRule {
        id: "mod_instance_failed",
        source: SourceKind::RuntimeLog,
        patterns: &["failed to create mod instance"],
        and_patterns: &[],
        category: CrashCategory::Mod,
        confidence: 0.70,
        reason: "Mod 初始化失败",
        suggestion: "某个 Mod 在创建实例时出错。\n请检查其前置 Mod 是否齐备，或尝试移除最近安装的 Mod。",
    },
    KeywordRule {
        id: "forge_exception_halt",
        source: SourceKind::RuntimeLog,
        patterns: &["an exception was thrown, the game will display an error screen and halt"],
        and_patterns: &[],
        category: CrashCategory::Forge,
        confidence: 0.75,
        reason: "Forge 运行异常并中止游戏",
        suggestion: "Forge 在运行中抛出异常并终止了游戏进程。\n请查阅日志定位具体报错，或重新安装该版本的 Forge。",
    },
    KeywordRule {
        id: "fabric_solution_determined",
        source: SourceKind::RuntimeLog,
        patterns: &["a potential solution has been determined"],
        and_patterns: &[],
        category: CrashCategory::Fabric,
        confidence: 0.70,
        reason: "Fabric 检测到错误并给出建议",
        suggestion: "Fabric 报告了错误，并在日志中给出了可能的解决方向。\n请按日志中 Fabric 提供的建议排查。",
    },
    // ── 崩溃报告 ──
    KeywordRule {
        id: "java_version_too_new",
        source: SourceKind::CrashReport,
        patterns: &["unable to make protected final java.lang.class java.lang.classloader.defineclass"],
        and_patterns: &[],
        category: CrashCategory::Java,
        confidence: 0.90,
        reason: "Java 版本过新导致启动失败",
        suggestion: "该错误通常由较新版本的 Java 引起。\n请在启动设置中为游戏选择较低版本的 Java，然后重新启动。",
    },
    KeywordRule {
        id: "mod_id_limit",
        source: SourceKind::CrashReport,
        patterns: &["maximum id range exceeded"],
        and_patterns: &[],
        category: CrashCategory::Mod,
        confidence: 0.85,
        reason: "已安装 Mod 超出注册表 ID 上限",
        suggestion: "当前安装的 Mod 数量过多，超过了游戏的 ID 上限。\n建议移除部分不常使用的 Mod。",
    },
    KeywordRule {
        id: "gpu_pixel_format_not_accelerated",
        source: SourceKind::CrashReport,
        patterns: &["pixel format not accelerated"],
        and_patterns: &[],
        category: CrashCategory::Graphics,
        confidence: 0.90,
        reason: "显卡驱动未启用像素格式加速",
        suggestion: "游戏所需的像素格式未获得硬件加速，通常与显卡驱动相关。\n请更新显卡驱动，或在启动设置中关闭「使用高性能显卡」后再试。",
    },
    KeywordRule {
        id: "manual_debug_crash",
        source: SourceKind::CrashReport,
        patterns: &["manually triggered debug crash"],
        and_patterns: &[],
        category: CrashCategory::Unknown,
        confidence: 0.90,
        reason: "手动触发的调试崩溃（F3+C）",
        suggestion: "这是通过调试快捷键主动触发的崩溃，游戏本身并未异常。",
    },
    KeywordRule {
        id: "mod_block_location",
        source: SourceKind::CrashReport,
        patterns: &["block location: world:"],
        and_patterns: &[],
        category: CrashCategory::Mod,
        confidence: 0.65,
        reason: "崩溃与特定方块相关",
        suggestion: "游戏在处理某个方块时发生崩溃。\n可以尝试定位并移除该方块（例如借助地图编辑工具清理）。",
    },
    KeywordRule {
        id: "mod_entity_location",
        source: SourceKind::CrashReport,
        patterns: &["entity's exact location:"],
        and_patterns: &[],
        category: CrashCategory::Mod,
        confidence: 0.65,
        reason: "崩溃与特定实体相关",
        suggestion: "游戏在处理某个实体时发生崩溃。\n建议定位并清理该实体后重试。",
    },
    // ── JVM 崩溃日志（hs_err）──
    KeywordRule {
        id: "mem_system_oom",
        source: SourceKind::HsErr,
        patterns: &["the system is out of physical ram or swap space", "out of memory error"],
        and_patterns: &[],
        category: CrashCategory::Memory,
        confidence: 0.95,
        reason: "系统内存不足（JVM 层面崩溃）",
        suggestion: "JVM 因物理内存或交换空间耗尽而退出。\n请降低游戏内存分配，或关闭其他占用内存的程序。\n若当前为 32 位 Java，请更换为 64 位。",
    },
    KeywordRule {
        id: "gpu_intel_driver",
        source: SourceKind::HsErr,
        patterns: &["exception_access_violation"],
        and_patterns: &["# c  [ig"],
        category: CrashCategory::Graphics,
        confidence: 0.90,
        reason: "Intel 显卡驱动导致 JVM 崩溃",
        suggestion: "JVM 崩溃与 Intel 显卡驱动相关（EXCEPTION_ACCESS_VIOLATION）。\n请将 Intel 显卡驱动升级到最新版本后重试。\n参考: https://bugs.mojang.com/browse/MC-32606",
    },
    KeywordRule {
        id: "gpu_amd_driver",
        source: SourceKind::HsErr,
        patterns: &["exception_access_violation"],
        and_patterns: &["# c  [atio"],
        category: CrashCategory::Graphics,
        confidence: 0.90,
        reason: "AMD 显卡驱动导致 JVM 崩溃",
        suggestion: "JVM 崩溃与 AMD 显卡驱动相关（EXCEPTION_ACCESS_VIOLATION）。\n请将 AMD 显卡驱动升级到最新版本后重试。\n参考: https://bugs.mojang.com/browse/MC-31618",
    },
    KeywordRule {
        id: "gpu_nvidia_driver",
        source: SourceKind::HsErr,
        patterns: &["exception_access_violation"],
        and_patterns: &["# c  [nvoglv"],
        category: CrashCategory::Graphics,
        confidence: 0.90,
        reason: "Nvidia 显卡驱动导致 JVM 崩溃",
        suggestion: "JVM 崩溃与 Nvidia 显卡驱动相关（EXCEPTION_ACCESS_VIOLATION）。\n请将 Nvidia 显卡驱动升级到最新版本后重试。",
    },
    KeywordRule {
        id: "jvm_access_violation",
        source: SourceKind::HsErr,
        patterns: &["exception_access_violation"],
        and_patterns: &[],
        category: CrashCategory::Unknown,
        confidence: 0.70,
        reason: "JVM 访问违规崩溃（EXCEPTION_ACCESS_VIOLATION）",
        suggestion: "Java 虚拟机触发了内存访问违规。\n该情况多与显卡驱动相关，请尝试更新驱动。\n若使用独立显卡，请确认 Java 正以高性能模式运行。",
    },
];
