/* Generated with cbindgen:0.29.4 */

/* This file was generated by cbindgen. DO NOT EDIT. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/* 不透明 SDK 句柄 (内部结构不对外暴露) */
typedef struct MC_SDK_SDKHandle MC_SDK_SDKHandle;

/*
 游戏 ID (Minecraft)
 */
#define MC_SDK_GAME_ID 432

/*
 SDK 错误码 (FFI 接口使用)
 */
enum MC_SDK_ErrorCode {
  /*
   成功
   */
  Success = 0,
  /*
   无效参数
   */
  InvalidArgument = 1,
  /*
   空指针
   */
  NullPointer = 2,
  /*
   内存不足
   */
  OutOfMemory = 3,
  /*
   IO 错误
   */
  IoError = 4,
  /*
   内部 panic
   */
  Panic = 5,
  /*
   未初始化
   */
  NotInitialized = 6,
  /*
   已初始化
   */
  AlreadyInitialized = 7,
  /*
   不支持的操作
   */
  Unsupported = 8,
  /*
   网络错误
   */
  NetworkError = 100,
  /*
   下载失败
   */
  DownloadFailed = 101,
  /*
   超时
   */
  TimeoutError = 102,
  /*
   无效响应
   */
  InvalidResponse = 103,
  /*
   HTTP 错误
   */
  HttpError = 104,
  /*
   认证失败
   */
  AuthFailed = 200,
  /*
   令牌过期
   */
  TokenExpired = 201,
  /*
   无效凭证
   */
  InvalidCredentials = 202,
  /*
   认证被拒绝
   */
  AuthDenied = 203,
  /*
   版本未找到
   */
  VersionNotFound = 300,
  /*
   版本解析错误
   */
  VersionParseError = 301,
  /*
   库文件缺失
   */
  LibraryMissing = 302,
  /*
   版本清单错误
   */
  ManifestError = 303,
  /*
   启动失败
   */
  LaunchFailed = 400,
  /*
   Java 未找到
   */
  JavaNotFound = 401,
  /*
   无效 Java 版本
   */
  InvalidJavaVersion = 402,
  /*
   进程错误
   */
  ProcessError = 403,
  /*
   JVM 参数错误
   */
  JvmArgsError = 404,
  /*
   文件未找到
   */
  FileNotFound = 500,
  /*
   文件损坏
   */
  FileCorrupted = 501,
  /*
   权限被拒绝
   */
  PermissionDenied = 502,
  /*
   磁盘空间不足
   */
  DiskSpaceInsufficient = 503,
  /*
   目录不存在
   */
  DirectoryNotFound = 504,
};

/*
 认证类型枚举
 */
enum MC_SDK_AuthType {
  /*
   微软账号
   */
  Microsoft = 0,
  /*
   离线模式
   */
  Offline = 1,
  /*
   外置认证 (Authlib-Injector)
   */
  External = 2,
};

/*
 错误信息结构体 (FFI 使用)
 */
struct MC_SDK_ErrorInfo {
  /*
   错误码
   */
  enum MC_SDK_ErrorCode mCode;
  /*
   错误消息 (UTF-8)
   */
  char *mMessage;
  /*
   详细信息 (可选)
   */
  char *mDetails;
};

/*
 SDK 配置结构体 (FFI 接口使用)
 */
struct MC_SDK_MCConfig {
  /*
   游戏目录路径 (UTF-8 编码)
   */
  const char *mGameDir;
  /*
   最大下载线程数 (默认 8)
   */
  uint32_t mMaxDownloadThreads;
  /*
   镜像源 URL (已废弃，保留向后兼容)
   */
  const char *mMirrorUrl;
  /*
   日志级别 (0=off, 1=error, 2=warn, 3=info, 4=debug, 5=trace)
   */
  uint32_t mLogLevel;
  /*
   CurseForge API Key (可选，为空指针表示不使用 CurseForge API)
   */
  const char *mCurseforgeApiKey;
  /*
   版本隔离模式 (0=无隔离, 1=隔离MOD版本, 2=隔离非正式版, 3=隔离MOD和正式版, 4=隔离所有)
   */
  uint32_t mIsolationMode;
  /*
   游戏窗口标题 (可选，为空指针使用默认标题)
   */
  const char *mWindowTitle;
  /*
   镜像源 URL (版本清单/JSON)，为空指针时回退到 mirror_url
   */
  const char *mMirrorUrlMeta;
  /*
   镜像源 URL (资源下载)，为空指针时回退到 mirror_url
   */
  const char *mMirrorUrlDownload;
  /*
   最大下载速度 (bytes/sec)，0=不限制
   */
  uint64_t mMaxDownloadSpeed;
  /*
   镜像模式 (0=手动, 1=自动探测降级)
   */
  uint32_t mMirrorMode;
};

/*
 系统内存信息结构体 (FFI 接口)
 */
struct MC_SDK_FFISystemMemory {
  /*
   总物理内存 (字节)
   */
  uint64_t mTotal;
  /*
   已使用内存 (字节)
   */
  uint64_t mUsed;
  /*
   可用内存 (字节)
   */
  uint64_t mAvailable;
  /*
   内存使用率 (0-100)
   */
  double mUsagePercent;
};

/*
 FFI 认证结果结构体
 */
struct MC_SDK_FFIAuthResult {
  /*
   认证类型
   */
  enum MC_SDK_AuthType mAuthType;
  /*
   访问令牌
   */
  char *mAccessToken;
  /*
   刷新令牌
   */
  char *mRefreshToken;
  /*
   玩家 UUID
   */
  char *mUuid;
  /*
   玩家用户名
   */
  char *mUsername;
  /*
   令牌过期时间
   */
  int64_t mExpiresAt;
  /*
   错误码 (0 = 成功)
   */
  int32_t mErrorCode;
  /*
   错误消息
   */
  char *mErrorMessage;
};

/*
 FFI 设备码信息结构体
 */
struct MC_SDK_FFIDeviceCode {
  /*
   设备码
   */
  char *mDeviceCode;
  /*
   用户码（显示给用户）
   */
  char *mUserCode;
  /*
   验证 URI
   */
  char *mVerificationUri;
  /*
   完整验证 URI
   */
  char *mVerificationUriComplete;
  /*
   过期时间（秒）
   */
  uint32_t mExpiresIn;
  /*
   轮询间隔（秒）
   */
  uint32_t mInterval;
  /*
   错误码 (0 = 成功)
   */
  int32_t mErrorCode;
  /*
   错误消息
   */
  char *mErrorMessage;
};

/*
 合并安装请求结构体 (FFI 接口使用)
 */
struct MC_SDK_FFIMergedInstallRequest {
  /*
   Minecraft 版本号 (必须)
   */
  const char *mMcVersion;
  /*
   Forge 版本号 (NULL = 跳过)
   */
  const char *mForgeVersion;
  /*
   NeoForge 版本号 (NULL = 跳过)
   */
  const char *mNeoforgeVersion;
  /*
   Fabric 版本号 (NULL = 跳过)
   */
  const char *mFabricVersion;
  /*
   OptiFine 版本号 (NULL = 跳过)
   */
  const char *mOptifineVersion;
  /*
   LiteLoader 版本号 (NULL = 跳过)
   */
  const char *mLiteloaderVersion;
  /*
   实例名称 (NULL = 默认使用 mc_version)
   */
  const char *mInstanceName;
};

/*
 FFI 版本条目结构体
 */
struct MC_SDK_FFIVersionEntry {
  /*
   版本 ID
   */
  char *mId;
  /*
   版本类型 (release/snapshot/old_beta/old_alpha)
   */
  char *mVersionType;
  /*
   发布时间 (Unix 时间戳)
   */
  int64_t mReleaseTime;
};

/*
 FFI 版本列表结构体
 */
struct MC_SDK_FFIVersionList {
  /*
   版本数组指针
   */
  struct MC_SDK_FFIVersionEntry *mVersions;
  /*
   版本数量
   */
  uint32_t mCount;
  /*
   最新正式版
   */
  char *mLatestRelease;
  /*
   最新快照版
   */
  char *mLatestSnapshot;
  /*
   错误码 (0 = 成功)
   */
  int32_t mErrorCode;
  /*
   错误消息
   */
  char *mErrorMessage;
};

struct MC_SDK_FFIJavaRuntime {
  char *mExecutable;
  char *mVersion;
  uint32_t mMajorVersion;
  char *mArch;
  char *mHome;
};

struct MC_SDK_FFIJavaList {
  struct MC_SDK_FFIJavaRuntime *mRuntimes;
  uint32_t mCount;
  int32_t mErrorCode;
  char *mErrorMessage;
};

struct MC_SDK_FFIUpdateInfo {
  char *mCurrentVersion;
  char *mLatestVersion;
  int32_t mUpdateAvailable;
  char *mDownloadUrl;
  char *mSha256;
  uint64_t mSize;
  char *mChangelog;
};

struct MC_SDK_FFIProgressSnapshot {
  uint32_t mStage;
  uintptr_t mCurrent;
  uintptr_t mTotal;
  uint64_t mBytesDownloaded;
  uint64_t mBytesTotal;
  uint64_t mSpeed;
  uintptr_t mFilesRemaining;
  bool mIsActive;
  bool mIsComplete;
  int32_t mErrorCode;
};

const struct MC_SDK_ErrorInfo *mc_sdk_last_error(void);

void mc_sdk_free_error(struct MC_SDK_ErrorInfo *aError);

void mc_sdk_clear_error(void);

/*
 初始化 SDK

 # Arguments
 * `config` - SDK 配置指针，不能为 null

 # Returns
 成功返回 SDK 句柄指针，失败返回 null

 # Safety
 - `config` 必须是有效的 MCConfig 指针
 - 返回的指针必须通过 `mc_sdk_free` 释放
 */
MC_SDK_SDKHandle *mc_sdk_init(const struct MC_SDK_MCConfig *aConfig);

/*
 释放 SDK 资源

 # Arguments
 * `handle` - SDK 句柄指针

 # Safety
 - `handle` 必须是通过 `mc_sdk_init` 返回的有效指针
 - 释放后不能再使用该指针
 */
void mc_sdk_free(MC_SDK_SDKHandle *aHandle);

/*
 获取 SDK 版本号

 # Returns
 版本字符串指针 (静态内存，无需释放)
 */
const char *mc_sdk_version(void);

/*
 检查 SDK 是否已初始化

 # Returns
 已初始化返回 1，未初始化返回 0
 */
int32_t mc_sdk_is_initialized(void);

/*
 获取游戏目录路径

 # Arguments
 * `handle` - SDK 句柄指针

 # Returns
 游戏目录路径字符串指针，失败返回 null
 返回的字符串必须通过 `mc_sdk_free_string` 释放

 # Safety
 - `handle` 必须是有效的 SDKHandle 指针
 */
char *mc_sdk_get_game_dir(const MC_SDK_SDKHandle *aHandle);

/*
 释放字符串内存

 # Arguments
 * `str` - 字符串指针

 # Safety
 - `str` 必须是通过 SDK 函数返回的有效指针
 */
void mc_sdk_free_string(char *aStr);

/*
 获取设备唯一标识

 返回当前设备的唯一标识符字符串。
 返回的字符串必须通过 `mc_sdk_free_string` 释放。

 # Returns
 设备唯一标识字符串指针，失败返回 null

 # Platform Support
 - Windows: 使用 MachineGuid 注册表键
 - macOS: 使用 IOPlatformUUID
 - Linux: 使用 /etc/machine-id
 */
char *mc_get_device_id(void);

/*
 获取系统内存信息

 返回当前系统的内存使用情况。
 无需 SDK 句柄，可直接调用。

 # Arguments
 * `memory_out` - 输出参数，接收内存信息

 # Returns
 0=成功，非0=错误码

 # Example
 ```c
 FFISystemMemory memory;
 if (mc_get_system_memory(&memory) == 0) {
     printf("Total: %llu MB\n", memory.total / 1024 / 1024);
     printf("Available: %llu MB\n", memory.available / 1024 / 1024);
     printf("Usage: %.1f%%\n", memory.usage_percent);
 }
 ```
 */
int32_t mc_get_system_memory(struct MC_SDK_FFISystemMemory *aMemoryOut);

/*
 加密 Token 数据

 使用 DES 加密，密钥为 "mcsdk-{设备码}"。
 返回的字符串必须通过 `mc_sdk_free_string` 释放。

 # Arguments
 * `data` - 明文数据 (JSON 字符串)

 # Returns
 加密后的数据 (Base64 编码)，失败返回 null
 */
char *mc_encrypt_token(const char *aData);

/*
 解密 Token 数据

 使用 DES 解密，密钥为 "mcsdk-{设备码}"。
 返回的字符串必须通过 `mc_sdk_free_string` 释放。

 # Arguments
 * `encrypted` - 加密后的数据 (Base64 编码)

 # Returns
 明文数据 (JSON 字符串)，失败返回 null
 */
char *mc_decrypt_token(const char *aEncrypted);

/*
 离线模式登录

 # Arguments
 * `username` - 玩家用户名
 * `result_out` - 输出参数，接收认证结果

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_auth_offline(const char *aUsername, struct MC_SDK_FFIAuthResult *aResultOut);

/*
 释放认证结果
 */
void mc_auth_free_result(struct MC_SDK_FFIAuthResult *aResult);

/*
 释放设备码信息
 */
void mc_auth_free_device_code(struct MC_SDK_FFIDeviceCode *aDeviceCode);

/*
 发起微软 OAuth 2.0 设备码登录
 */
int32_t mc_auth_microsoft_start(struct MC_SDK_FFIDeviceCode *aDeviceCodeOut);

/*
 轮询微软 OAuth 2.0 设备码登录状态
 */
int32_t mc_auth_microsoft_poll(const char *aDeviceCode, uint32_t aInterval, struct MC_SDK_FFIAuthResult *aResultOut);

/*
 刷新微软 OAuth 2.0 令牌
 */
int32_t mc_auth_microsoft_refresh(const char *aRefreshToken, struct MC_SDK_FFIAuthResult *aResultOut);

/*
 Mojang 认证登录
 */
int32_t mc_auth_mojang_login(const char *aUsername, const char *aPassword, struct MC_SDK_FFIAuthResult *aResultOut);

/*
 统一通行证登录
 */
int32_t mc_auth_nide_login(const char *aServerId, const char *aUsername, const char *aPassword, struct MC_SDK_FFIAuthResult *aResultOut);

/*
 Authlib-Injector 登录
 */
int32_t mc_auth_authlib_login(const char *aBaseUrl, const char *aUsername, const char *aPassword, struct MC_SDK_FFIAuthResult *aResultOut);

/*
 获取玩家皮肤信息
 */
int32_t mc_skin_get(const char *aUuid, char **aSkinOut);

/*
 上传皮肤
 */
int32_t mc_skin_upload(const char *aAccessToken, const char *aSkinPath, const char *aVariant, char **aProfileOut);

/*
 设置当前披风
 */
int32_t mc_skin_set_cape(const char *aAccessToken, const char *aCapeId, char **aProfileOut);

/*
 取消当前披风
 */
int32_t mc_skin_clear_cape(const char *aAccessToken, char **aProfileOut);

/*
 下载版本文件

 # Arguments
 * `handle` - SDK 句柄
 * `version_id` - 版本 ID (如 "1.20.1")
 * `callback` - 进度回调函数 (可选，传 NULL 表示不需要回调)
 * `user_data` - 用户数据指针

 # Returns
 0=成功，非0=错误码

 # Callback Signature
 ```c
 /**
 * 下载进度回调函数类型
 *
 * # Arguments
 * * `stage` - 当前阶段名称
 * * `current` - 当前完成数量
 * * `total` - 总数量
 * * `bytes_downloaded` - 已下载字节数
 * * `bytes_total` - 总字节数
 * * `speed` - 下载速度 (bytes/sec)
 * * `files_remaining` - 剩余文件数量
 * * `user_data` - 用户数据指针
 */
typedef void (*FFICallback)(const char* stage, uintptr_t current, uintptr_t total, uint64_t bytes_downloaded, uint64_t bytes_total, uint64_t speed, uintptr_t files_remaining, void* user_data);
 ```
 - stage: 当前阶段名称字符串，如 "Downloading Libraries"
 - current: 当前已完成数量
 - total: 总数量
 - user_data: 用户传入的指针
 */
int32_t mc_download_version(const MC_SDK_SDKHandle *aHandle, const char *aVersionId, const void *aCallback, void *aUserData);

/*
 CurseForge 搜索结果 JSON 字符串
 返回的字符串必须通过 `mc_sdk_free_string` 释放
 */
int32_t mc_curseforge_search(const char *aApiKey, const char *aQuery, const char *aGameVersion, uint32_t aPage, uint32_t aPageSize, char **aResultOut);

/*
 Modrinth 搜索结果 JSON 字符串
 返回的字符串必须通过 `mc_sdk_free_string` 释放
 */
int32_t mc_modrinth_search(const char *aQuery, const char *aGameVersion, uint32_t aLimit, uint32_t aOffset, char **aResultOut);

/*
 安装整合包

 # Arguments
 * `handle` - SDK 句柄
 * `modpack_path` - 整合包路径
 * `result_out` - 输出参数，接收安装结果
 * `callback` - 进度回调函数 (可选，传 NULL 表示不需要回调)
 * `user_data` - 用户数据指针

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_install_modpack(const MC_SDK_SDKHandle *aHandle, const char *aModpackPath, char **aResultOut, const void *aCallback, void *aUserData);

/*
 CurseForge 获取项目详情
 */
int32_t mc_curseforge_get_project(const char *aApiKey, uint32_t aProjectId, char **aResultOut);

/*
 CurseForge 获取项目文件列表
 */
int32_t mc_curseforge_get_files(const char *aApiKey, uint32_t aProjectId, const char *aGameVersion, uint32_t aPage, uint32_t aPageSize, char **aResultOut);

/*
 Modrinth 获取项目详情
 */
int32_t mc_modrinth_get_project(const char *aProjectId, char **aResultOut);

/*
 Modrinth 获取项目版本列表
 */
int32_t mc_modrinth_get_versions(const char *aProjectId, const char *aGameVersion, const char *aLoader, char **aResultOut);

/*
 启动游戏

 # Arguments
 * `handle` - SDK 句柄
 * `username` - 玩家用户名
 * `uuid` - 玩家 UUID
 * `access_token` - 访问令牌
 * `version_id` - 版本 ID
 * `max_memory` - 最大内存 (MB)

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_launch_game(const MC_SDK_SDKHandle *aHandle, const char *aUsername, const char *aUuid, const char *aAccessToken, const char *aVersionId, uint32_t aMaxMemory);

/*
 启动游戏 (扩展版本，支持更多参数)

 # Arguments
 * `handle` - SDK 句柄
 * `username` - 玩家用户名
 * `uuid` - 玩家 UUID
 * `access_token` - 访问令牌
 * `version_id` - 版本 ID
 * `min_memory` - 最小内存 (MB)，传 0 使用默认值 (max_memory/2)
 * `max_memory` - 最大内存 (MB)，传 0 使用默认值 (1024)
 * `window_width` - 窗口宽度，传 0 使用默认值 (854)
 * `window_height` - 窗口高度，传 0 使用默认值 (480)
 * `server_address` - 服务器地址 (可选，传 NULL 不自动加入服务器)
 * `server_port` - 服务器端口 (可选，传 0 使用默认端口 25565)
 * `java_path` - Java 可执行文件路径 (可选，传 NULL 自动检测)

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_launch_game_ex(const MC_SDK_SDKHandle *aHandle, const char *aUsername, const char *aUuid, const char *aAccessToken, const char *aVersionId, uint32_t aMinMemory, uint32_t aMaxMemory, uint32_t aWindowWidth, uint32_t aWindowHeight, const char *aServerAddress, uint32_t aServerPort, const char *aJavaPath);

/*
 获取游戏进程状态

 返回进程状态码：
 - 0: 未启动
 - 1: 运行中
 - 2: 已退出（成功）
 - 3: 已退出（失败）
 - 4: 已终止
 */
int32_t mc_launch_get_status(void);

/*
 获取游戏进程退出码

 返回退出码，如果进程还在运行或未启动返回 -1
 */
int32_t mc_launch_get_exit_code(void);

/*
 获取 Mod 列表

 返回 Mod 列表的 JSON 字符串。
 返回的字符串必须通过 `mc_sdk_free_string` 释放。
 */
int32_t mc_mod_list(const MC_SDK_SDKHandle *aHandle, char **aResultOut);

/*
 启用 Mod

 将 .disabled 文件重命名为 .jar
 */
int32_t mc_mod_enable(const MC_SDK_SDKHandle *aHandle, const char *aModPath);

/*
 禁用 Mod

 将 .jar 文件重命名为 .disabled
 */
int32_t mc_mod_disable(const MC_SDK_SDKHandle *aHandle, const char *aModPath);

/*
 安装 Forge

 # Arguments
 * `handle` - SDK 句柄
 * `mc_version` - Minecraft 版本号
 * `forge_version` - Forge 版本号
 * `callback` - 进度回调函数 (可选，传 NULL 表示不需要回调)
 * `user_data` - 用户数据指针

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_install_forge(const MC_SDK_SDKHandle *aHandle, const char *aMcVersion, const char *aForgeVersion, const void *aCallback, void *aUserData);

/*
 安装 Fabric

 # Arguments
 * `handle` - SDK 句柄
 * `mc_version` - Minecraft 版本号
 * `loader_version` - Fabric Loader 版本号
 * `callback` - 进度回调函数 (可选，传 NULL 表示不需要回调)
 * `user_data` - 用户数据指针

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_install_fabric(const MC_SDK_SDKHandle *aHandle, const char *aMcVersion, const char *aLoaderVersion, const void *aCallback, void *aUserData);

/*
 安装 NeoForge

 # Arguments
 * `handle` - SDK 句柄
 * `mc_version` - Minecraft 版本号
 * `neoforge_version` - NeoForge 版本号
 * `callback` - 进度回调函数 (可选，传 NULL 表示不需要回调)
 * `user_data` - 用户数据指针

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_install_neoforge(const MC_SDK_SDKHandle *aHandle, const char *aMcVersion, const char *aNeoforgeVersion, const void *aCallback, void *aUserData);

/*
 安装 OptiFine

 # Arguments
 * `handle` - SDK 句柄
 * `mc_version` - Minecraft 版本号
 * `optifine_version` - OptiFine 版本号
 * `callback` - 进度回调函数 (可选，传 NULL 表示不需要回调)
 * `user_data` - 用户数据指针

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_install_optifine(const MC_SDK_SDKHandle *aHandle, const char *aMcVersion, const char *aOptifineVersion, const void *aCallback, void *aUserData);

/*
 安装 LiteLoader

 # Arguments
 * `handle` - SDK 句柄
 * `mc_version` - Minecraft 版本号
 * `liteloader_version` - LiteLoader 版本号
 * `callback` - 进度回调函数 (可选，传 NULL 表示不需要回调)
 * `user_data` - 用户数据指针

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_install_liteloader(const MC_SDK_SDKHandle *aHandle, const char *aMcVersion, const char *aLiteloaderVersion, const void *aCallback, void *aUserData);

/*
 合并安装: 下载 MC + 选定的加载器，一次调用完成。

 流程: 下载原版 MC → 按顺序安装每个加载器。
 进度回调报告各阶段的总体进度。

 # Arguments
 * `handle` - SDK 句柄
 * `request` - 合并安装请求
 * `callback` - 进度回调函数 (可选，传 NULL 表示不需要回调)
 * `user_data` - 用户数据指针

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_install_merged(const MC_SDK_SDKHandle *aHandle, const struct MC_SDK_FFIMergedInstallRequest *aRequest, const void *aCallback, void *aUserData);

/*
 释放版本列表
 */
void mc_free_version_list(struct MC_SDK_FFIVersionList *aVersionList);

/*
 获取 Minecraft 版本列表

 从官方源或镜像源获取所有可用的 Minecraft 版本。
 返回的版本列表必须通过 `mc_free_version_list` 释放。

 # Arguments
 * `handle` - SDK 句柄（可选，传 NULL 使用官方源）
 * `version_list_out` - 输出参数，接收版本列表

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_list_versions(const MC_SDK_SDKHandle *aHandle, struct MC_SDK_FFIVersionList *aVersionListOut);

/*
 获取可用的 Forge 版本列表

 返回 JSON 字符串: `["47.2.0", "47.1.0", ...]`
 返回的字符串必须通过 `mc_sdk_free_string` 释放。

 # Arguments
 * `handle` - SDK 句柄
 * `mc_version` - Minecraft 版本号
 * `result_out` - 输出参数，接收 JSON 字符串

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_list_forge_versions(const MC_SDK_SDKHandle *aHandle, const char *aMcVersion, char **aResultOut);

/*
 获取可用的 NeoForge 版本列表

 返回 JSON 字符串: `[{"version":"47.2","recommended":false}, ...]`
 返回的字符串必须通过 `mc_sdk_free_string` 释放。

 # Arguments
 * `handle` - SDK 句柄
 * `mc_version` - Minecraft 版本号
 * `result_out` - 输出参数，接收 JSON 字符串

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_list_neoforge_versions(const MC_SDK_SDKHandle *aHandle, const char *aMcVersion, char **aResultOut);

/*
 获取可用的 Fabric Loader 版本列表

 返回 JSON 字符串: `[{"version":"0.15.0","stable":true}, ...]`
 返回的字符串必须通过 `mc_sdk_free_string` 释放。

 # Arguments
 * `handle` - SDK 句柄
 * `result_out` - 输出参数，接收 JSON 字符串

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_list_fabric_versions(const MC_SDK_SDKHandle *aHandle, char **aResultOut);

/*
 获取可用的 OptiFine 版本列表

 返回 JSON 字符串: `[{"display_name":"1.20.1 HD U I7","is_preview":false}, ...]`
 返回的字符串必须通过 `mc_sdk_free_string` 释放。

 # Arguments
 * `handle` - SDK 句柄
 * `result_out` - 输出参数，接收 JSON 字符串

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_list_optifine_versions(const MC_SDK_SDKHandle *aHandle, char **aResultOut);

/*
 获取可用的 LiteLoader 版本列表

 返回 JSON 字符串: `["1.20.1", ...]` (过滤出指定 MC 版本的版本号)
 返回的字符串必须通过 `mc_sdk_free_string` 释放。

 # Arguments
 * `handle` - SDK 句柄
 * `mc_version` - Minecraft 版本号
 * `result_out` - 输出参数，接收 JSON 字符串

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_list_liteloader_versions(const MC_SDK_SDKHandle *aHandle, const char *aMcVersion, char **aResultOut);

/*
 验证加载器兼容性

 返回 0 表示兼容，非 0 表示不兼容 (设置 last_error 描述冲突原因)。

 规则 (同 PCL2):
 - Forge + Fabric = 不兼容
 - Forge + NeoForge = 不兼容
 - NeoForge + Fabric = 不兼容
 - NeoForge + OptiFine = 不兼容
 - Forge 1.13~1.14.3 + OptiFine = 不兼容
 - Fabric 1.20.5+ + OptiFine = 不兼容

 # Arguments
 * `mc_version` - Minecraft 版本号 (必须)
 * `forge_version` - Forge 版本号 (NULL 表示未选择)
 * `neoforge_version` - NeoForge 版本号 (NULL 表示未选择)
 * `fabric_version` - Fabric 版本号 (NULL 表示未选择)
 * `optifine_version` - OptiFine 版本号 (NULL 表示未选择)

 # Returns
 0=兼容，非0=不兼容 (ErrorCode::Unsupported)
 */
int32_t mc_validate_loaders(const char *aMcVersion, const char *aForgeVersion, const char *aNeoforgeVersion, const char *aFabricVersion, const char *aOptifineVersion);

/*
 获取已安装的版本列表

 扫描游戏目录，返回已安装的版本 ID 列表。
 返回的字符串数组必须通过 `mc_free_string_array` 释放。

 # Arguments
 * `handle` - SDK 句柄
 * `versions_out` - 输出参数，接收版本 ID 数组
 * `count_out` - 输出参数，接收版本数量

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_list_installed_versions(const MC_SDK_SDKHandle *aHandle, char ***aVersionsOut, uint32_t *aCountOut);

/*
 释放字符串数组

 # Arguments
 * `array` - 字符串数组指针
 * `count` - 数组长度
 */
void mc_free_string_array(char **aArray, uint32_t aCount);

void mc_free_java_list(struct MC_SDK_FFIJavaList *aJavaList);

void mc_free_java_runtime(struct MC_SDK_FFIJavaRuntime *aJavaRuntime);

int32_t mc_detect_java(struct MC_SDK_FFIJavaRuntime *aJavaOut);

int32_t mc_list_java(struct MC_SDK_FFIJavaList *aJavaListOut);

int32_t mc_update_check(const MC_SDK_SDKHandle *aHandle, struct MC_SDK_FFIUpdateInfo *aInfoOut);

int32_t mc_update_download(const MC_SDK_SDKHandle *aHandle, const char *aDownloadUrl, const char *aSha256, const char *aOutputPath, const void *aCallback, void *aUserData);

int32_t mc_update_install(const MC_SDK_SDKHandle *aHandle, const char *aUpdatePath, const char *aLatestVersion);

void mc_update_free_info(struct MC_SDK_FFIUpdateInfo *aInfo);

char *mc_config_get_game_dir(const MC_SDK_SDKHandle *aHandle);

char *mc_config_get_mirror(const MC_SDK_SDKHandle *aHandle);

char *mc_config_get_mirror_meta(const MC_SDK_SDKHandle *aHandle);

char *mc_config_get_mirror_download(const MC_SDK_SDKHandle *aHandle);

uint64_t mc_config_get_max_download_speed(const MC_SDK_SDKHandle *aHandle);

int32_t mc_network_clear_cache(const MC_SDK_SDKHandle *aHandle);

int32_t mc_get_progress(struct MC_SDK_FFIProgressSnapshot *aSnapshotOut);

int32_t mc_reset_progress(void);

int32_t mc_is_downloading(void);

int32_t mc_set_window_title(uint32_t aProcessId, const char *aTitleTemplate);

int32_t mc_stop_window_title(void);
