/* Generated with cbindgen:0.29.4 */

/* This file was generated by cbindgen. DO NOT EDIT. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 游戏 ID (Minecraft)
 */
#define MC_SDK_GAME_ID 432

/*
 认证类型枚举
 */
enum MC_SDK_AuthType {
  /*
   微软账号
   */
  Microsoft = 0,
  /*
   离线模式
   */
  Offline = 1,
  /*
   外置认证 (Authlib-Injector)
   */
  External = 2,
};

/*
 SDK 错误码 (FFI 接口使用)
 */
enum MC_SDK_ErrorCode {
  /*
   成功
   */
  Success = 0,
  /*
   无效参数
   */
  InvalidArgument = 1,
  /*
   空指针
   */
  NullPointer = 2,
  /*
   内存不足
   */
  OutOfMemory = 3,
  /*
   IO 错误
   */
  IoError = 4,
  /*
   内部 panic
   */
  Panic = 5,
  /*
   未初始化
   */
  NotInitialized = 6,
  /*
   已初始化
   */
  AlreadyInitialized = 7,
  /*
   不支持的操作
   */
  Unsupported = 8,
  /*
   网络错误
   */
  NetworkError = 100,
  /*
   下载失败
   */
  DownloadFailed = 101,
  /*
   超时
   */
  TimeoutError = 102,
  /*
   无效响应
   */
  InvalidResponse = 103,
  /*
   HTTP 错误
   */
  HttpError = 104,
  /*
   认证失败
   */
  AuthFailed = 200,
  /*
   令牌过期
   */
  TokenExpired = 201,
  /*
   无效凭证
   */
  InvalidCredentials = 202,
  /*
   认证被拒绝
   */
  AuthDenied = 203,
  /*
   版本未找到
   */
  VersionNotFound = 300,
  /*
   版本解析错误
   */
  VersionParseError = 301,
  /*
   库文件缺失
   */
  LibraryMissing = 302,
  /*
   版本清单错误
   */
  ManifestError = 303,
  /*
   启动失败
   */
  LaunchFailed = 400,
  /*
   Java 未找到
   */
  JavaNotFound = 401,
  /*
   无效 Java 版本
   */
  InvalidJavaVersion = 402,
  /*
   进程错误
   */
  ProcessError = 403,
  /*
   JVM 参数错误
   */
  JvmArgsError = 404,
  /*
   文件未找到
   */
  FileNotFound = 500,
  /*
   文件损坏
   */
  FileCorrupted = 501,
  /*
   权限被拒绝
   */
  PermissionDenied = 502,
  /*
   磁盘空间不足
   */
  DiskSpaceInsufficient = 503,
  /*
   目录不存在
   */
  DirectoryNotFound = 504,
};

/*
 SDK 配置结构体 (FFI 接口使用)
 */
struct MC_SDK_MCConfig {
  /*
   游戏目录路径 (UTF-8 编码)
   */
  const char *mGameDir;
  /*
   最大下载线程数 (默认 8)
   */
  uint32_t mMaxDownloadThreads;
  /*
   镜像源 URL (可选，为空指针表示使用官方源)
   */
  const char *mMirrorUrl;
  /*
   日志级别 (0=off, 1=error, 2=warn, 3=info, 4=debug, 5=trace)
   */
  uint32_t mLogLevel;
  /*
   CurseForge API Key (可选，为空指针表示不使用 CurseForge API)
   */
  const char *mCurseforgeApiKey;
};

/*
 FFI 认证结果结构体
 */
struct MC_SDK_FFIAuthResult {
  /*
   认证类型
   */
  enum MC_SDK_AuthType mAuthType;
  /*
   访问令牌
   */
  char *mAccessToken;
  /*
   刷新令牌
   */
  char *mRefreshToken;
  /*
   玩家 UUID
   */
  char *mUuid;
  /*
   玩家用户名
   */
  char *mUsername;
  /*
   令牌过期时间
   */
  int64_t mExpiresAt;
  /*
   错误码 (0 = 成功)
   */
  int32_t mErrorCode;
  /*
   错误消息
   */
  char *mErrorMessage;
};

/*
 FFI 设备码信息结构体
 */
struct MC_SDK_FFIDeviceCode {
  /*
   设备码
   */
  char *mDeviceCode;
  /*
   用户码（显示给用户）
   */
  char *mUserCode;
  /*
   验证 URI
   */
  char *mVerificationUri;
  /*
   完整验证 URI
   */
  char *mVerificationUriComplete;
  /*
   过期时间（秒）
   */
  uint32_t mExpiresIn;
  /*
   轮询间隔（秒）
   */
  uint32_t mInterval;
  /*
   错误码 (0 = 成功)
   */
  int32_t mErrorCode;
  /*
   错误消息
   */
  char *mErrorMessage;
};

/*
 FFI 进度回调函数类型
 */
typedef void (*MC_SDK_FFICallback)(const char *stage, uintptr_t current, uintptr_t total, void *user_data);

/*
 FFI 版本条目结构体
 */
struct MC_SDK_FFIVersionEntry {
  /*
   版本 ID
   */
  char *mId;
  /*
   版本类型 (release/snapshot/old_beta/old_alpha)
   */
  char *mVersionType;
  /*
   发布时间 (Unix 时间戳)
   */
  int64_t mReleaseTime;
};

/*
 FFI 版本列表结构体
 */
struct MC_SDK_FFIVersionList {
  /*
   版本数组指针
   */
  struct MC_SDK_FFIVersionEntry *mVersions;
  /*
   版本数量
   */
  uint32_t mCount;
  /*
   最新正式版
   */
  char *mLatestRelease;
  /*
   最新快照版
   */
  char *mLatestSnapshot;
  /*
   错误码 (0 = 成功)
   */
  int32_t mErrorCode;
  /*
   错误消息
   */
  char *mErrorMessage;
};

/*
 FFI Java 运行时信息结构体
 */
struct MC_SDK_FFIJavaRuntime {
  /*
   Java 可执行文件路径
   */
  char *mExecutable;
  /*
   Java 版本号
   */
  char *mVersion;
  /*
   Java 主版本号 (8, 11, 17, 21 等)
   */
  uint32_t mMajorVersion;
  /*
   Java 架构 (x86_64, aarch64 等)
   */
  char *mArch;
  /*
   Java 主页目录
   */
  char *mHome;
};

/*
 FFI Java 列表结构体
 */
struct MC_SDK_FFIJavaList {
  /*
   Java 数组指针
   */
  struct MC_SDK_FFIJavaRuntime *mRuntimes;
  /*
   Java 数量
   */
  uint32_t mCount;
  /*
   错误码 (0 = 成功)
   */
  int32_t mErrorCode;
  /*
   错误消息
   */
  char *mErrorMessage;
};

/*
 FFI 更新信息结构体
 */
struct MC_SDK_FFIUpdateInfo {
  /*
   当前版本
   */
  char *mCurrentVersion;
  /*
   最新版本
   */
  char *mLatestVersion;
  /*
   是否需要更新 (1=需要, 0=不需要)
   */
  int32_t mUpdateAvailable;
  /*
   下载 URL
   */
  char *mDownloadUrl;
  /*
   SHA-256 哈希
   */
  char *mSha256;
  /*
   文件大小 (字节)
   */
  uint64_t mSize;
  /*
   更新日志
   */
  char *mChangelog;
};

/*
 错误信息结构体 (FFI 使用)
 */
struct MC_SDK_ErrorInfo {
  /*
   错误码
   */
  enum MC_SDK_ErrorCode mCode;
  /*
   错误消息 (UTF-8)
   */
  char *mMessage;
  /*
   详细信息 (可选)
   */
  char *mDetails;
};

/*
 初始化 SDK

 # Arguments
 * `config` - SDK 配置指针，不能为 null

 # Returns
 成功返回 SDK 句柄指针，失败返回 null

 # Safety
 - `config` 必须是有效的 MCConfig 指针
 - 返回的指针必须通过 `mc_sdk_free` 释放
 */
MC_SDK_SDKHandle *mc_sdk_init(const struct MC_SDK_MCConfig *aConfig);

/*
 释放 SDK 资源

 # Arguments
 * `handle` - SDK 句柄指针

 # Safety
 - `handle` 必须是通过 `mc_sdk_init` 返回的有效指针
 - 释放后不能再使用该指针
 */
void mc_sdk_free(MC_SDK_SDKHandle *aHandle);

/*
 获取 SDK 版本号

 # Returns
 版本字符串指针 (静态内存，无需释放)
 */
const char *mc_sdk_version(void);

/*
 检查 SDK 是否已初始化

 # Returns
 已初始化返回 1，未初始化返回 0
 */
int32_t mc_sdk_is_initialized(void);

/*
 获取游戏目录路径

 # Arguments
 * `handle` - SDK 句柄指针

 # Returns
 游戏目录路径字符串指针，失败返回 null
 返回的字符串必须通过 `mc_sdk_free_string` 释放

 # Safety
 - `handle` 必须是有效的 SDKHandle 指针
 */
char *mc_sdk_get_game_dir(const MC_SDK_SDKHandle *aHandle);

/*
 释放字符串内存

 # Arguments
 * `str` - 字符串指针

 # Safety
 - `str` 必须是通过 SDK 函数返回的有效指针
 */
void mc_sdk_free_string(char *aStr);

/*
 获取设备唯一标识

 返回当前设备的唯一标识符字符串。
 返回的字符串必须通过 `mc_sdk_free_string` 释放。

 # Returns
 设备唯一标识字符串指针，失败返回 null

 # Platform Support
 - Windows: 使用 MachineGuid 注册表键
 - macOS: 使用 IOPlatformUUID
 - Linux: 使用 /etc/machine-id
 */
char *mc_get_device_id(void);

/*
 加密 Token 数据

 使用 DES 加密，密钥为 "mcsdk-{设备码}"。
 返回的字符串必须通过 `mc_sdk_free_string` 释放。

 # Arguments
 * `data` - 明文数据 (JSON 字符串)

 # Returns
 加密后的数据 (Base64 编码)，失败返回 null
 */
char *mc_encrypt_token(const char *aData);

/*
 解密 Token 数据

 使用 DES 解密，密钥为 "mcsdk-{设备码}"。
 返回的字符串必须通过 `mc_sdk_free_string` 释放。

 # Arguments
 * `encrypted` - 加密后的数据 (Base64 编码)

 # Returns
 明文数据 (JSON 字符串)，失败返回 null
 */
char *mc_decrypt_token(const char *aEncrypted);

/*
 离线模式登录

 # Arguments
 * `username` - 玩家用户名
 * `result_out` - 输出参数，接收认证结果

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_auth_offline(const char *aUsername, struct MC_SDK_FFIAuthResult *aResultOut);

/*
 释放认证结果
 */
void mc_auth_free_result(struct MC_SDK_FFIAuthResult *aResult);

/*
 释放设备码信息
 */
void mc_auth_free_device_code(struct MC_SDK_FFIDeviceCode *aDeviceCode);

/*
 发起微软 OAuth 2.0 设备码登录
 */
int32_t mc_auth_microsoft_start(struct MC_SDK_FFIDeviceCode *aDeviceCodeOut);

/*
 轮询微软 OAuth 2.0 设备码登录状态
 */
int32_t mc_auth_microsoft_poll(const char *aDeviceCode, uint32_t aInterval, struct MC_SDK_FFIAuthResult *aResultOut);

/*
 刷新微软 OAuth 2.0 令牌
 */
int32_t mc_auth_microsoft_refresh(const char *aRefreshToken, struct MC_SDK_FFIAuthResult *aResultOut);

/*
 Mojang 认证登录
 */
int32_t mc_auth_mojang_login(const char *aUsername, const char *aPassword, struct MC_SDK_FFIAuthResult *aResultOut);

/*
 统一通行证登录
 */
int32_t mc_auth_nide_login(const char *aServerId, const char *aUsername, const char *aPassword, struct MC_SDK_FFIAuthResult *aResultOut);

/*
 Authlib-Injector 登录
 */
int32_t mc_auth_authlib_login(const char *aBaseUrl, const char *aUsername, const char *aPassword, struct MC_SDK_FFIAuthResult *aResultOut);

/*
 获取玩家皮肤信息
 */
int32_t mc_skin_get(const char *aUuid, char **aSkinOut);

/*
 上传皮肤
 */
int32_t mc_skin_upload(const char *aAccessToken, const char *aSkinPath, const char *aVariant, char **aProfileOut);

/*
 设置当前披风
 */
int32_t mc_skin_set_cape(const char *aAccessToken, const char *aCapeId, char **aProfileOut);

/*
 取消当前披风
 */
int32_t mc_skin_clear_cape(const char *aAccessToken, char **aProfileOut);

/*
 下载版本文件

 # Arguments
 * `handle` - SDK 句柄
 * `version_id` - 版本 ID (如 "1.20.1")
 * `callback` - 进度回调函数
 * `user_data` - 用户数据指针

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_download_version(const MC_SDK_SDKHandle *aHandle, const char *aVersionId, MC_SDK_FFICallback aCallback, void *aUserData);

/*
 CurseForge 搜索结果 JSON 字符串
 返回的字符串必须通过 `mc_sdk_free_string` 释放
 */
int32_t mc_curseforge_search(const char *aApiKey, const char *aQuery, const char *aGameVersion, uint32_t aPage, uint32_t aPageSize, char **aResultOut);

/*
 Modrinth 搜索结果 JSON 字符串
 返回的字符串必须通过 `mc_sdk_free_string` 释放
 */
int32_t mc_modrinth_search(const char *aQuery, const char *aGameVersion, uint32_t aLimit, uint32_t aOffset, char **aResultOut);

/*
 安装整合包
 */
int32_t mc_install_modpack(const MC_SDK_SDKHandle *aHandle, const char *aModpackPath, char **aResultOut);

/*
 CurseForge 获取项目详情
 */
int32_t mc_curseforge_get_project(const char *aApiKey, uint32_t aProjectId, char **aResultOut);

/*
 CurseForge 获取项目文件列表
 */
int32_t mc_curseforge_get_files(const char *aApiKey, uint32_t aProjectId, const char *aGameVersion, uint32_t aPage, uint32_t aPageSize, char **aResultOut);

/*
 Modrinth 获取项目详情
 */
int32_t mc_modrinth_get_project(const char *aProjectId, char **aResultOut);

/*
 Modrinth 获取项目版本列表
 */
int32_t mc_modrinth_get_versions(const char *aProjectId, const char *aGameVersion, const char *aLoader, char **aResultOut);

/*
 启动游戏

 # Arguments
 * `handle` - SDK 句柄
 * `username` - 玩家用户名
 * `uuid` - 玩家 UUID
 * `access_token` - 访问令牌
 * `version_id` - 版本 ID
 * `max_memory` - 最大内存 (MB)

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_launch_game(const MC_SDK_SDKHandle *aHandle, const char *aUsername, const char *aUuid, const char *aAccessToken, const char *aVersionId, uint32_t aMaxMemory);

/*
 获取游戏进程状态

 返回进程状态码：
 - 0: 未启动
 - 1: 运行中
 - 2: 已退出（成功）
 - 3: 已退出（失败）
 - 4: 已终止
 */
int32_t mc_launch_get_status(void);

/*
 获取游戏进程退出码

 返回退出码，如果进程还在运行返回 -1
 */
int32_t mc_launch_get_exit_code(void);

/*
 获取 Mod 列表

 返回 Mod 列表的 JSON 字符串。
 返回的字符串必须通过 `mc_sdk_free_string` 释放。
 */
int32_t mc_mod_list(const MC_SDK_SDKHandle *aHandle, char **aResultOut);

/*
 启用 Mod

 将 .disabled 文件重命名为 .jar
 */
int32_t mc_mod_enable(const MC_SDK_SDKHandle *aHandle, const char *aModPath);

/*
 禁用 Mod

 将 .jar 文件重命名为 .disabled
 */
int32_t mc_mod_disable(const MC_SDK_SDKHandle *aHandle, const char *aModPath);

/*
 安装 Forge

 # Arguments
 * `handle` - SDK 句柄
 * `mc_version` - Minecraft 版本号
 * `forge_version` - Forge 版本号

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_install_forge(const MC_SDK_SDKHandle *aHandle, const char *aMcVersion, const char *aForgeVersion);

/*
 安装 Fabric

 # Arguments
 * `handle` - SDK 句柄
 * `mc_version` - Minecraft 版本号
 * `loader_version` - Fabric Loader 版本号

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_install_fabric(const MC_SDK_SDKHandle *aHandle, const char *aMcVersion, const char *aLoaderVersion);

/*
 安装 NeoForge

 # Arguments
 * `handle` - SDK 句柄
 * `mc_version` - Minecraft 版本号
 * `neoforge_version` - NeoForge 版本号

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_install_neoforge(const MC_SDK_SDKHandle *aHandle, const char *aMcVersion, const char *aNeoforgeVersion);

/*
 安装 OptiFine

 # Arguments
 * `handle` - SDK 句柄
 * `mc_version` - Minecraft 版本号
 * `optifine_version` - OptiFine 版本号

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_install_optifine(const MC_SDK_SDKHandle *aHandle, const char *aMcVersion, const char *aOptifineVersion);

/*
 安装 LiteLoader

 # Arguments
 * `handle` - SDK 句柄
 * `mc_version` - Minecraft 版本号
 * `liteloader_version` - LiteLoader 版本号

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_install_liteloader(const MC_SDK_SDKHandle *aHandle, const char *aMcVersion, const char *aLiteloaderVersion);

/*
 释放版本列表
 */
void mc_free_version_list(struct MC_SDK_FFIVersionList *aVersionList);

/*
 获取 Minecraft 版本列表

 从官方源或镜像源获取所有可用的 Minecraft 版本。
 返回的版本列表必须通过 `mc_free_version_list` 释放。

 # Arguments
 * `version_list_out` - 输出参数，接收版本列表

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_list_versions(struct MC_SDK_FFIVersionList *aVersionListOut);

/*
 获取已安装的版本列表

 扫描游戏目录，返回已安装的版本 ID 列表。
 返回的字符串数组必须通过 `mc_free_string_array` 释放。

 # Arguments
 * `handle` - SDK 句柄
 * `versions_out` - 输出参数，接收版本 ID 数组
 * `count_out` - 输出参数，接收版本数量

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_list_installed_versions(const MC_SDK_SDKHandle *aHandle, char ***aVersionsOut, uint32_t *aCountOut);

/*
 释放字符串数组

 # Arguments
 * `array` - 字符串数组指针
 * `count` - 数组长度
 */
void mc_free_string_array(char **aArray, uint32_t aCount);

/*
 释放 Java 列表
 */
void mc_free_java_list(struct MC_SDK_FFIJavaList *aJavaList);

/*
 释放 Java 运行时信息
 */
void mc_free_java_runtime(struct MC_SDK_FFIJavaRuntime *aJavaRuntime);

/*
 检测最佳 Java 运行时

 自动检测系统中已安装的 Java，并返回最佳版本。
 要求 Java 8 或更高版本。

 # Arguments
 * `java_out` - 输出参数，接收 Java 运行时信息

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_detect_java(struct MC_SDK_FFIJavaRuntime *aJavaOut);

/*
 列出所有已安装的 Java 运行时

 返回的列表必须通过 `mc_free_java_list` 释放。

 # Arguments
 * `java_list_out` - 输出参数，接收 Java 列表

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_list_java(struct MC_SDK_FFIJavaList *aJavaListOut);

/*
 检查 SDK 更新

 # Arguments
 * `handle` - SDK 句柄
 * `info_out` - 输出参数，接收更新信息

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_update_check(const MC_SDK_SDKHandle *aHandle, struct MC_SDK_FFIUpdateInfo *aInfoOut);

/*
 下载 SDK 更新

 # Arguments
 * `handle` - SDK 句柄
 * `download_url` - 下载 URL
 * `sha256` - SHA-256 哈希 (可选，为空指针跳过验证)
 * `output_path` - 输出文件路径

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_update_download(const MC_SDK_SDKHandle *aHandle, const char *aDownloadUrl, const char *aSha256, const char *aOutputPath);

/*
 安装 SDK 更新

 # Arguments
 * `handle` - SDK 句柄
 * `update_path` - 更新包路径
 * `latest_version` - 最新版本号

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_update_install(const MC_SDK_SDKHandle *aHandle, const char *aUpdatePath, const char *aLatestVersion);

/*
 释放更新信息

 # Arguments
 * `info` - 更新信息指针
 */
void mc_update_free_info(struct MC_SDK_FFIUpdateInfo *aInfo);

/*
 获取游戏目录

 返回的字符串必须通过 `mc_sdk_free_string` 释放。

 # Arguments
 * `handle` - SDK 句柄

 # Returns
 游戏目录路径字符串，失败返回 null
 */
char *mc_config_get_game_dir(const MC_SDK_SDKHandle *aHandle);

/*
 获取镜像源 URL

 返回的字符串必须通过 `mc_sdk_free_string` 释放。
 如果未设置镜像源，返回空字符串。

 # Arguments
 * `handle` - SDK 句柄

 # Returns
 镜像源 URL 字符串，失败返回 null
 */
char *mc_config_get_mirror(const MC_SDK_SDKHandle *aHandle);

/*
 清除 HTTP 缓存

 # Arguments
 * `handle` - SDK 句柄

 # Returns
 0=成功，非0=错误码
 */
int32_t mc_network_clear_cache(const MC_SDK_SDKHandle *aHandle);

const struct MC_SDK_ErrorInfo *mc_sdk_last_error(void);

void mc_sdk_free_error(struct MC_SDK_ErrorInfo *aError);

void mc_sdk_clear_error(void);
